default: &default
  adapter: postgresql

test:
  <<: *default
  database: all_sorns_test

development:
  <<: *default
  host: db
  username: postgres
  password:
  encoding: unicode

production:
  <<: *default
  database: all_sorns_production