---
name: Deploy to prod

on:
  workflow_run:
    workflows: ["Deploy to test"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    if: github.repository_owner == '18F' && ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy to cloud.gov prod space
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install cf cli
        run: |
          curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | sudo tar -zx --directory=/usr/local/bin
          cf --version
      - name: Deploy to cloud.gov
        env:
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_ORG: ${{ secrets.CF_ORG }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
          CF_CGHOSTNAME: test
        run: ./.cloud-gov/deploy.sh rolling
