---
name: Deploy to test

on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    if: github.repository_owner == '18F' && ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy to cloud.gov test space
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy app
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_username: ${{ secrets.CF_USERNAME_TEST }}
          cf_password: ${{ secrets.CF_PASSWORD_TEST }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE_TEST }}
          cf_command: CF_SPACE=${{ secrets.CF_SPACE_TEST }} CGHOSTNAME=all-sorns-test .cloud-gov/deploy.sh rolling
