---
name: "Find SORNs"

on:
  schedule:
    - cron: "11 7 * * 1-5"  # 2:11am eastern, m-f
  workflow_dispatch:

jobs:
  find-sorns:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install cf cli
        run: brew install cloudfoundry/tap/cf-cli
      - name: Login and update
        run: |
          cf api https://api.fr.cloud.gov
          cf auth ${{ vars.CF_USERNAME }} ${{ secrets.CF_PASSWORD }}
          cf target -o ${{ vars.CF_ORG }} -s ${{ vars.CF_SPACE }}
          cf run-task all_sorns --command "bundle exec rails federal_register:find_sorns" --name "Find SORNs"
          echo "Daily update queued"
