---
name: "Find SORNs"

on:
  schedule:
    - cron: "11 7 * * 1-5"  # 2:11am eastern, m-f
  workflow_dispatch:

jobs:
  find-sorns:
    if: github.repository_owner == '18F'
    runs-on: ubuntu-latest
    steps:
      - name: Run update task
        uses: 18f/cg-deploy-action@main
        with:
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
          full_command: |
            cf run-task all_sorns "bundle exec rails federal_register:find_sorns" --name "Find SORNs"
