---
name: "Find SORNs"

on:
  schedule:
    - cron: "11 7 * * 1-5"  # 2:11am eastern, m-f
  workflow_dispatch:

jobs:
  find-sorns:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update SORNs
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_username: ${{ vars.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ vars.CF_ORG }}
          cf_space: ${{ vars.CF_SPACE }}
          cf_command: run-task all_sorns --command "bundle exec rails federal_register:find_sorns" --name "Find SORNs"
